### ISSUE TITLE
Improve Registry Manager to work in Windows and support more commands

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS-Incubator/registry#37]
- [x] Registry manager should work in Windows and Linux
- [x] Add load-data command to import files generated by Harvest
- [x] Implement delete-data command in Java
- [x] Add export-file command to export a file from a blob storage
- [x] Add create-registry command to create registry collection in Solr.
- [x] Add delete-registry command to delete registry collection from Solr.

**Comment by rchenatjpl** [comment]
For testing, I've run this on a mac and linux but not a pc. I have no access to such a machine. Sorry. We can blame the pandemic.

**Comment by jordanpadams** [comment]
@rchenatjpl we actually do have a windows server Geosciences Node setup for us... but @tdddblog uses a windows machine so i think this has been sufficiently tested for Registry
